### ISSUE TITLE
🐛 OAuth 에 대한 오류

### ISSUE THREAD

**Issue by jeongyunnim** [bitbit-Merry-go-round/Transcendence-BE#35]
## 🔎 어떤 버그인가요?
- OAuth 시 이미 존재하는 유저가 있으면 에러가 발생해요..

## 📝 어떤 상황에서 발생한 버그인가요?
- OAuth로 로그인한 뒤 다시 로그인으로 돌아갈 경우 에러 발생

## 🧪 예상 결과
> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

## ✅ To-do
- [x] 중복 설정값 수정
- [x] User 모델 수정
- [x] 변경된 User 모델에 맞게 기존 코드 수정

## 📚 참고할만한 자료

<img width="964" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/68039396-9454-4be9-840a-944f0f3857a7">

```python
class SocialLogin(object):
"""
    Represents a social user that is in the process of being logged in. This consists of the following information:

    `account` (`SocialAccount` instance): The social account being logged in. Providers are not responsible for checking whether or not an account already exists or not. Therefore, a provider typically creates a new (unsaved) `SocialAccount` instance. The `User` instance pointed to by the account (`account.user`) may be prefilled by the provider for use as a starting point later on during the signup process.

    `token` (`SocialToken` instance): An optional access token token that results from performing a successful authentication handshake.

    `state` (`dict`): The state to be preserved during the authentication handshake. Note that this state may end up in the url -- do not put any secrets in here. It currently only contains the url to redirect to after login.

    `email_addresses` (list of `EmailAddress`): Optional list of email addresses retrieved from the provider.
"""
```

위의 객체의 프로퍼티

<img width="676" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/3f8d6e7b-3fb9-4f89-ae0e-713a5ea42b18">

**Comment by Seotephen** [comment]
<img width="830" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/c5d6e430-a413-4d8c-a2fb-6ce300a4cd74">

AUTH_USER_MODEL이 중복되어있어요

**Comment by ohhamma** [comment]
찾아주셔서 감사합니다 🥹 빠르게 수정하겠습니다!
