### ISSUE TITLE
🐛 사용자 입력 오류 처리

### ISSUE THREAD

**Issue by ohhamma** [bitbit-Merry-go-round/Transcendence-BE#46]
## 🔎 어떤 버그인가요?
- `5xx` 에러를 `4xx`으로 처리해서 응답

## 📝 어떤 상황에서 발생한 버그인가요?
- 존재하지 않는 `username`이 요청으로 들어온 경우
  - 프로필 조회, 프로필 수정, 친구 조회 : URI
  - 친구 추가 : URI, body
- 존재하지 않는 `friend`가 **삭제** 요청으로 들어온 경우 (URL)
- 이미 존재하는 `friend`가 **추가** 요청으로 들어온 경우 (body)
- 존재하지 않는 `refresh`가 요청으로 들어온 경우
  - 로그아웃 : body
- 비어 있는 `bearer token`이 요청으로 들어온 경우
  - gateway에서 처리

## 🧪 예상 결과
- 각 예외 상황에 대하셔 `5xx` 에러가 아니라 `4xx` 에러로 처리되어야 함
  - URI가 유효하지 않은 경우 → 404
  - body가 유효하지 않은 경우 → 400
  - token이 유효하지 않은 경우 → 401

## ✅ To-do
- [x] 유효하지 않은 `username` 처리
- [x] #58
- [x] 이미 존재하는 `friend` 처리 (추가)
- [x] 유효하지 않은 `refresh` 처리
- [x] 비어 있는 `bearer token` 처리

## 📚 참고할만한 자료
> 선택사항입니다
