### ISSUE TITLE
🐛 게임 중복 데이터 추가에 대한 오류

### ISSUE THREAD

**Issue by ohhamma** [bitbit-Merry-go-round/Transcendence-BE#60]
## 🔎 어떤 버그인가요?
- 중복 게임 및 토너먼트를 추가할 수 있음

## 📝 어떤 상황에서 발생한 버그인가요?
- 중복된 내용의 게임이나 토너먼트를 추가했을 때 정상적으로 추가됨

## 🧪 예상 결과
- 중복 내용의 게임이나 토너먼트 추가 시 `400` 에러 발생

## ✅ To-do
- [x] 중복 게임 및 중복 토너먼트 기준 세우기
- [x] 중복 게임 추가 막기
- [x] 중복 토너먼트 추가 막기

## 📚 참고할만한 자료
> 선택사항입니다
